#Settings
CLIENT_VERSION = 1.4
SERVER_HOST = "teosoft.ipcasa.net" #192.168.8.219
SERVER_PORT = 25565
SERVER_ADDR = (SERVER_HOST, SERVER_PORT)
SERVER_ADDR_STR = SERVER_ADDR[0] + ":" + str(SERVER_ADDR[1])
CLIENT_SCREEN_SIZE = (1600, 900)
CLIENT_SCREEN_TITLE = "Anime Battle v" + str(CLIENT_VERSION)
MENU_SCREEN_SIZE = (400,300)
MENU_ACTIVADO = False
NUMERO_JUGADORES_ESCOGIBLES = 5
NUMERO_CANCIONES_DISPONIBLES = 3
mPEscogido = 0
